### ISSUE TITLE
Front controller

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#51]
## Entry Points

The different channels each need their own entry point, since the application stack will be different in some regard.
- [x] Entry point for browsers `index.php`
- [ ] Entry point for web services `api.php`
- [x] Entry point for command line access `joomla.php`
## Router Middleware

Each entrypoint needs its own router, which maps incoming data to commands.
- [x] Web Router, see #59
- [ ] Legacy Router
- [ ] API Router
- [x] CLI Router
## Dynamic Middleware

> This section does not belong to the `CDH` milestone.

Some middleware will be added at runtime. Thus, a "dynamic middleware" is needed, which identifies the middleware, and adds them to the application stack in the right order.
- [ ] `DynamicMiddleware`
- [ ] Administration for dynamic middleware (enable, disable, ordering)
