### ISSUE TITLE
ORM

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#54]
## Repositories
- [ ] Evaluate [PINQ](http://elliotswebsite.com/Pinq).
  Based off the .NET's LINQ (Language integrated query), PINQ unifies querying across arrays/iterators and external data sources, in a single readable and concise fluent API. Using this for the Repository implementation would make a lot of things (especially testing) much easier.
## Storage

The storage layer is hidden behind an abstraction, the ORM. It allows to use different storage engines and technologies transparently.
- [x] Doctrine DBAL Adapter
- [x] CSV Adapter, see PR#115
- [ ] Schema Builder, see #101

**Comment by laoneo** [comment]
ORM is implemented trough the ORM library https://github.com/joomla-projects/joomla-pythagoras/tree/clean-base/libraries/incubator/ORM
