### ISSUE TITLE
Renderer

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#60]
## Channel Dependant Renderers

Each possible output channel might require its own output format. The `Accept:` header is used to determine the requested format. For channels without such a header, like CLI, a fake header is created.

The `Accept:` header contains a MIME type. The MIME types are assigned to Renderers using an editable map.
- [x] MIME Mapping
- [x] JSON Renderer
- [x] XML Renderer
- [x] Plain Text Renderer
- [x] HTML Renderer
## Script Strategies

The HTML Renderer supports script strategies, i.e., classes that abstract JavaScript libraries.
- [ ] Plain, i.e., no JavaScript
- [ ] Vanilla JavaScript
- [ ] Bootstrap 4, see #82
## Templating

Some Renderers, like HTML, will need a templating system.
- [x] Define Templating, see #100 
- [x] Define default List View, see #103 
- [x] Define default Detail View, see #102 
- [ ] Define default Form View, see #104
## Possible Enhancements

These things could be beneficial; they are up to discussion.
- [Jason](http://www.jasonbase.com/) lets you instantly turn any data, website, or API into your own custom app. It would require its own Renderer.

**Comment by laoneo** [comment]
Is actually in heavy development https://github.com/joomla-projects/joomla-pythagoras/tree/clean-base/libraries/incubator/Renderer. Closing this one as there will be more fine grained renderer related PR's made in the future.
